### ISSUE TITLE
Third party orders

### ISSUE THREAD

**Issue by kanzelsberger** [Zasilkovna/magento2#1]
Is it possible to create Zasielkovna shipping and label for orders that were checked out using a different shipping method? For example we have a flat rate or best rate where we decide the best shipping method for customer. 

When we decide to ship using Zasielkovna to let's say France, we would welcome a feature that would allow us to create a shipping and label for any order.

Also support for all EU countries (supported by Zasielkovna) would be really great as we ship mostly to different EU countries.

**Comment by MatyasKoval** [comment]
Hello,
we are currently not considering supporting other delivery methods but since the 2.1.0 version, our plugin supports Zasilkovna's external carriers for home delivery. Since version 2.0.3 our plugin supports delivery to pickup places all around Europe (including the pickup points of external carriers). 
As of now, we currently do not support delivery outside of EU.

Best regards,
Matyáš Kovaľ
