### ISSUE TITLE
Fatal type error if quote address is empty

### ISSUE THREAD

**Issue by sevka** [Zasilkovna/magento2#40]
### Error
I installed the module, but for me it doesn't work. If I enable shipping methods in admin panel, the checkout page is constantly failing with the following fatal error:

`Argument 2 passed to Packetery\Checkout\Model\Carrier\AbstractBrain::isAvailableForCollection() must be of the type string, null given, called in XXX/Model/Carrier/AbstractBrain.php on line 209`

### Cause of the error

I investigated it a little bit. The type error happens when the quote address is not set yet (table quote_address). In this case the country_id = NULL, so  in this file \Packetery\Checkout\Model\Carrier\AbstractBrain::collectRates()
when you call isAvailableForCollection(), the argument 2 is NULL:
`$this->isAvailableForCollection($selectedMethod, $request->getDestCountryId(), $dynamicCarrier) `

But it is declared as a string here:
\Packetery\Checkout\Model\Carrier\AbstractBrain::isAvailableForCollection()

`protected function isAvailableForCollection(string $method, string $countryId, ?AbstractDynamicCarrier $dynamicCarrier = null): bool
`
The same for  \Packetery\Checkout\Model\Carrier\AbstractBrain::resolvePointId():
`public function resolvePointId(string $method, string $countryId, ?AbstractDynamicCarrier $dynamicCarrier = null): ?int`

### How to reproduce
1. Enable Packetery shipping methods
2. Create a new customer, or delete the current quote from the DB (table quote).
3. Add some product to the cart
4. Open cart page

Could you fix this, please?

**Comment by packeta** [comment]
What Magento version are you running? Only Magento 2.3 and 2.4 is supported. What module version are you using?

**Comment by sevka** [comment]
Sorry, I forgot to add.
Magento Commerce 2.4.2-p1
Module version 2.2.0 (the last version from your GitHub master branch.

**Comment by FJiskra** [comment]
Hello,

i tested Packeta module version 2.2.0 without changes in Magento 2.4.2 and it is working fine. It is working fine in Magento 2.4.3 as well. I followed your reproduction steps. I suggest migrating to Magento version 2.4.3.

I suggest not to delete any data manually from database unless you know all the consequences.

It seems to me that either there is bug in your version or you installed other module that changes expected behavior or the Magento instance is incorrectly installed. Magento claims in its code documentation that getDestCountryId() always returns string. Empty destination country is not supported by module pricing rules.

I would like to know if following changes fix your problem. Can you please test them? Please make sure you followed installation steps mentioned in README.md

https://github.com/Zasilkovna/magento2/tree/PES-337_country_is_null_bug

Please make sure you have pricing rules configured in order to create Packeta order.

**Comment by sevka** [comment]
@FJiskra 
Sorry for the delay. Yes, this change you implemented fixed the issue:
https://github.com/Zasilkovna/magento2/compare/PES-337_country_is_null_bug

Can you merge it to the new version?
Thanks
